=================================
How to Use 101-lazy_matrix_mul.py
=================================

This module introduces a matrix multiplication function called
``lazy_matrix_mul(m_a, m_b)``.

Usage
=====

``lazy_matrix_mul(...)`` produces a new matrix that embodies the result of multiplying
``m_a`` by ``m_b``.

::

    >>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
    >>> m_a = [
    ... [1, 2],
    ... [3, 4],
    ... ]
    >>> m_b = m_a
    >>> lazy_matrix_mul(m_a, m_b)
    [[ 7 10]
     [15 22]]

::

    >>> m_a = [[1, 2]]
    >>> m_b = [
    ... [3, 4],
    ... [5, 6]
    ... ]
    >>> lazy_matrix_mul(m_a, m_b)
    [[13 16]]

The function seamlessly handles floating-point numbers.

::

    >>> m_a = [
    ... [1.2, 5.5, 6.2],
    ... [4.66, 12.3, -9.2]
    ... ]
    >>> m_b = [
    ... [5.0, 3.3],
    ... [-2.9, 4.4],
    ... [7.2, 4.4]
    ... ]
    >>> lazy_matrix_mul(m_a, m_b)
    [[ 34.69   55.44 ]
     [-78.61   29.018]]

A minimum of two arguments must be provided.

::

    >>> print(lazy_matrix_mul(m_a))
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() demands 1 more positional argument: 'm_b'

::

    >>> print(lazy_matrix_mul()) # doctest: +NORMALIZE_WHITESPACE
    Traceback (most recent call last):
    TypeError: lazy_matrix_mul() demands 2 positional arguments: 
    'm_a' and 'm_b'

ValueErrors
===========

If two matrices cannot engage in multiplication (i.e., the row count of ``m_a`` does not
equal the column count in ``m_b``), a ValueError steps into the spotlight.

::

    >>> m_a = [
    ... [1, 2],
    ... [3, 4],
    ... ]
    >>> m_b = [
    ... [1, 2],
    ... [2, 3],
    ... [4, 5]
    ... ]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)


The parameters ``m_a`` and ``m_b`` cannot play hide-and-seek in emptiness. Otherwise,
a ValueError will call them out.

::

    >>> lazy_matrix_mul([[]], [[5, 6], [7, 8]])
    Traceback (most recent call last):
    ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

::

    >>> lazy_matrix_mul([[5, 6], [7, 8]], [[]])
    Traceback (most recent call last):
    ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

Invalid Matrices
================

The parameters ``m_a`` and ``m_b`` should not be impostors. If either of them pretends
to be a list, a ValueError is unforgiving.

::

    >>> lazy_matrix_mul("not a list", [[1, 2]])
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

::

    >>> lazy_matrix_mul([[1, 2]], "also not a list")
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

::

    >>> lazy_matrix_mul("not a list", "also not a list")
    Traceback (most recent call last):
    ValueError: Scalar operands are not allowed, use '*' instead

If either parameter is ``None``, a TypeError is raised.

::

    >>> lazy_matrix_mul(None, None)
    Traceback (most recent call last):
    TypeError: Object arrays are not currently supported

Not just any list - they *must* be lists of lists! Otherwise, behavior is
undefined.

::

    >>> lazy_matrix_mul([1, 2], [[3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

::

    >>> lazy_matrix_mul([[1, 2]], [3, 4])
    [11]

::

    >>> lazy_matrix_mul([1, 2], [3, 4])
    11

And not just any list of lists - they *must* be lists of lists containing
integers or floats! Otherwise, a ValueError or TypeError is raised

::

    >>> lazy_matrix_mul([[1, "non-number"]], [[3, 4]])
    Traceback (most recent call last):
    ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

::

    >>> lazy_matrix_mul([[5, 6], [7, 8]], [[5, "6"], [7, 8]])
    Traceback (most recent call last):
    TypeError: invalid data type for einsum

::

    >>> lazy_matrix_mul([[1, "non-number"]], [[{"a": 1}, 8.8]])
    Traceback (most recent call last):
    TypeError: Object arrays are not currently supported

Finally, the length of all rows in matrices ``m_a`` and ``m_b`` should be
equivalent. Otherwise, a ValueError is raised.

::

    >>> m_a = [
    ... [1, 2],
    ... [3, 4, 5]
    ... ]
    >>> m_b = [
    ... [1, 2],
    ... [3, 4]
    ... ]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.

::

    >>> m_a = [
    ... [1, 2],
    ... [3, 4]
    ... ]
    >>> m_b = [
    ... [1, 2],
    ... [3, 4, 5]
    ... ]
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.

::

    >>> m_a = [
    ... [1, 2],
    ... [3, 4, 5]
    ... ]
    >>> m_b = m_a
    >>> lazy_matrix_mul(m_a, m_b)
    Traceback (most recent call last):
    ValueError: setting an array element with a sequence.
